### ISSUE TITLE
process.env.PACKAGES isn't set in build:dev or build:prod

### ISSUE THREAD

**Issue by mrpotatoes** [psychobolt/react-rollup-boilerplate#1]
Running the `build:*` after installing && bootstrapping will lead to the following error:

```
rollup -c rollup.config.dev.js
[!] TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/Users/alibresinn/Desktop/react-rollup-boilerplate/rollup.config.dev.js:15:39)
    at Module._compile (module.js:649:30)
    at Object.require.extensions..js (/Users/alibresinn/Desktop/react-rollup-boilerplate/node_modules/rollup/bin/rollup:1270:24)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /Users/alibresinn/Desktop/react-rollup-boilerplate/node_modules/rollup/bin/rollup:1277:32
    at <anonymous>

error Command failed with exit code 1.
```

Cheers!

**Comment by psychobolt** [comment]
Thanks, I'll take a look at it
